// github_dotnet/New folder/ascendion-fsd-jan-2025/demos/workshops-app/src/app/workshops/workshop-details/add-session/add-session.component.ts
import { Component } from '@angular/core';
import {
  AbstractControl,
  FormBuilder,
  FormGroup,
  FormControl,
  NgForm,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { JsonPipe } from '@angular/common';

import { ToastService } from '../../../common/toast.service';

import { SessionsService } from '../../sessions.service';
import ISession from '../../models/ISession';

function durationAndLevel(form: AbstractControl) {
  const durationStr = (form.get('duration') as AbstractControl).value;
  const duration = +durationStr;
  const level = (form.get('level') as AbstractControl).value;

  // if valid -> return null
  // if invalid -> return an object with the details of the error. Further this object should have the property called `durationAndLevel`
  if (durationStr === '' || level === '') {
    return null;
  }

  if (level === 'Basic') {
    return null;
  }

  if (level === 'Intermediate') {
    if (duration >= 2) {
      return null;
    }

    // error
    return {
      durationAndLevel:
        'Intermediate level session should be at least 2 hours in duration',
    };
  }

  if (level === 'Advanced') {
    if (duration >= 3) {
      return null;
    }

    // error
    return {
      durationAndLevel:
        'Advanced level session should be at least 3 hours in duration',
    };
  }

  return null;
}

@Component({
  selector: 'app-add-session',
  standalone: true,
  imports: [ReactiveFormsModule, JsonPipe],
  templateUrl: './add-session.component.html',
  styleUrl: './add-session.component.scss',
})
export class AddSessionComponent {
  addSessionForm: FormGroup;

  // helper accessor methods
  get sequenceId() {
    return this.addSessionForm.get('sequenceId') as FormControl;
  }

  get name() {
    return this.addSessionForm.get('name') as FormControl;
  }

  get speaker() {
    return this.addSessionForm.get('speaker') as FormControl;
  }

  get duration() {
    return this.addSessionForm.get('duration') as FormControl;
  }

  get level() {
    return this.addSessionForm.get('level') as FormControl;
  }

  get abstract() {
    return this.addSessionForm.get('abstract') as FormControl;
  }

  constructor(
    private activatedRoute: ActivatedRoute,
    private sessionsService: SessionsService,
    private router: Router,
    private toastService: ToastService,
    private fb: FormBuilder
  ) {
    this.addSessionForm = this.fb.group(
      {
        sequenceId: [
          '', // initial value of the input
          [
            // the list of validators
            Validators.required,
            Validators.pattern('\\d+'),
          ],
        ],
        name: [
          '',
          [Validators.required, Validators.pattern('[A-Z][A-Za-z ]+')],
        ],
        speaker: [
          '',
          [
            Validators.required,
            Validators.pattern('[A-Z][A-Za-z ]+(,[A-Z ][A-Za-z ]+)*'),
          ],
        ],
        duration: [
          '',
          [Validators.required, Validators.min(0.5), Validators.max(10)],
        ],
        level: ['', [Validators.required]],
        abstract: ['', [Validators.required, Validators.minLength(2)]],
      },
      {
        // setting up cross-field validators
        validators: durationAndLevel,
      }
    );
  }

  addSession() {
    const id = +(this.activatedRoute.snapshot.parent?.paramMap.get(
      'id'
    ) as string);

    const newSession = {
      workshopId: id,
      upvoteCount: 0,
      sequenceId: +this.sequenceId.value,
      speaker: this.speaker.value,
      name: this.name.value,
      level: this.level.value,
      duration: +this.duration.value,
      abstract: this.abstract.value,
    } as Omit<ISession, 'id'>;

    console.log(newSession);

    this.sessionsService.addSession(newSession).subscribe({
      next: (addedSession) => {
        this.toastService.add({
          message: `Added session with id = ${addedSession.id}`,
          className: 'bg-success text-light',
          duration: 5000,
        });

        // You can also use navigateByUrl()
        this.router.navigate(['/workshops', id]);
      },
      error: (error) => {
        this.toastService.add({
          message: `Unable to add the session - ${error.message}`,
          className: 'bg-danger text-light',
          duration: 5000,
        });
      },
    });
  }
}

<div class="d-flex justify-content-between align-items-center">
  <h2 class="my-3">Add a session</h2>
  <button class="btn btn-primary" id="list-sessions">List of sessions</button>
</div>

<hr />

<form
  id="add-session-form"
  (ngSubmit)="addSession()"
  [formGroup]="addSessionForm"
  novalidate
>
  <div class="mb-3 error-message">
    @if( addSessionForm.errors && addSessionForm.errors['durationAndLevel'] ) {
    <div>{{ addSessionForm.errors["durationAndLevel"] }}</div>
    }
  </div>
  <div class="mb-3">
    <label for="sequenceId" class="form-label">Sequence ID</label>

    <!--
      [formControl]="sequenceId"
    -->
    <input
      type="text"
      class="form-control"
      id="sequenceId"
      name="sequenceId"
      formControlName="sequenceId"
      autocomplete="off"
    />
    <!-- Note how the JSON pipe is used for inspecting objects and thus useful for debugging! -->
    {{ sequenceId.errors | json }}
    {{ sequenceId.value }}
    <div>{{ "sequenceId.invalid = " + sequenceId.invalid }}</div>
    <div>{{ "sequenceId.valid = " + sequenceId.valid }}</div>
    <div>{{ "sequenceId.dirty =" + sequenceId.dirty }}</div>
    <div>{{ "sequenceId.touched =" + sequenceId.touched }}</div>

    @if( sequenceId.invalid && ( sequenceId.touched || sequenceId.dirty ) &&
    sequenceId.errors ) {
    <div class="error-message">
      @if(sequenceId.errors['required']) {
      <div>This is required</div>
      } @if(sequenceId.errors['pattern']) {
      <div>Provide a number</div>
      }
    </div>
    }
  </div>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" formControlName="name" />
  </div>
  <div class="mb-3">
    <label for="speaker" class="form-label">Speaker</label>
    <input
      type="text"
      class="form-control"
      id="speaker"
      formControlName="speaker"
    />
  </div>
  <div class="mb-3">
    <label for="duration" class="form-label">Duration</label>
    <input
      type="number"
      class="form-control"
      id="duration"
      formControlName="duration"
    />
  </div>
  <div class="mb-3">
    <label for="level" class="form-label">Level</label>
    <select class="form-select" id="level" formControlName="level">
      <option value="Basic">Basic</option>
      <option value="Intermediate">Intermediate</option>
      <option value="Advanced">Advanced</option>
    </select>
  </div>
  <div class="mb-3">
    <label for="abstract" class="form-label">Abstract</label>
    <textarea
      class="form-control"
      id="abstract"
      rows="3"
      formControlName="abstract"
    ></textarea>
  </div>
  <div class="mb-3">
    <button class="btn btn-primary">
      Add session
    </button>
  </div>
</form>

// ReactTs/CompleteReactTsAfterTraining/ascendion-react-feb-2025/demos/03-redux/workshops-app/src/components/workshops/WorkshopDetails/AddSession/AddSession.tsx
import { useForm } from 'react-hook-form';
import { Link, useNavigate } from 'react-router-dom';
import { Button, Form } from "react-bootstrap"

import { addSession } from '../../../../services/sessions';
import { Level } from '../../../../models/ISession';
interface Props {
    id: number
}

interface SessionFormType {
    sequenceId: number;
    name: string;
    speaker: string;
    duration: number;
    level: Level;
    abstract: string;
}

// React Hook Form uncontrolled components
const AddSession = ( { id } : Props) => {
    const { register, formState: { errors, isValid }, getValues, handleSubmit } = useForm<SessionFormType>({
        mode: 'all' // all events like change, blur, submit of form will trigger validatons
    });

    const navigate = useNavigate();

    const onSubmit = async (values : SessionFormType) => {

        const session = {
            ...values,
            sequenceId: +values.sequenceId,
            duration: +values.duration,
            upvoteCount: 0,
            workshopId: id
        };

        console.log( session );

        // POST the new session information to create a new session
        try {
            const newSession = await addSession( session );
            // alert('New session has been added');
            navigate( '../' ); // or navigate('/workshops/${id}')
        } catch(error) {
            alert((error as Error).message);
        }
    }

    const checkDurationAgainstLevel = () => {
        const duration = getValues('duration');
        const level = getValues('level');

        if( level === 'Basic' && duration < 1 ) {
            return false;
        }

        if( level === 'Intermediate' && duration < 2 ) {
            return false;
        }

        if( level === 'Advanced' && duration < 3 ) {
            return false;
        }

        return true;
    }

    return (
        <div>
            <h1 className="d-flex justify-content-between align-items-center">
                Add a Session
                <Link to=".." className="btn btn-primary">List of sessions</Link>
            </h1>

            <hr />

            {/* handleSubmit(onSubmit) returns a function */}
            {/* handleSubmit ensures that onSubmit is called only when the form is valid */}
            {/* the broswer form submission is prevented */}
            <Form onSubmit={handleSubmit(onSubmit)}>
                <Form.Group className="mb-4" controlId="sequenceId">
                    <Form.Label>Sequence ID</Form.Label>
                    <Form.Control
                        type="number"
                        placeholder="The Sequence ID of the session (eg. 1, 2, 3...)"
                        {...register('sequenceId', { required: true, pattern: /^\d+$/ })}
                    />
                    {
                        errors.sequenceId && (
                            <>
                                {
                                    errors.sequenceId.type === 'required' && <div>This field is required</div>
                                }
                                {
                                    errors.sequenceId.type === 'pattern' && <div>This should be a positive number</div>
                                }
                            </>
                        )
                    }
                </Form.Group>
                <Form.Group className="mb-4" controlId="name">
                    <Form.Label>Name</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Name of the session, Eg. Introduction to Programming"
                        {...register('name', { required: true, pattern: /^[A-Za-z0-9][A-Za-z0-9 ]+$/ })}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="speaker">
                    <Form.Label>Speaker</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Name of the speaker(s). Eg. John Doe, Jane Doe"
                        {...register('speaker', { required: true, pattern: /^[A-Za-z][A-Za-z ]+$/ })}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="duration">
                    <Form.Label>Duration</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="The duration of the session in hours (eg. 2.5)"
                        {...register('duration', { required: true, pattern: /^\d+(.\d+)?$/ })}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="level">
                    <Form.Label>Level</Form.Label>
                    <Form.Select
                        aria-label="Level"
                        {...register('level', { required: true, validate: checkDurationAgainstLevel })}
                    >
                        <option disabled>-- Select the level --</option>
                        <option value="Basic">Basic</option>
                        <option value="Intermediate">Intermediate</option>
                        <option value="Advanced">Advanced</option>
                    </Form.Select>
                </Form.Group>
                {
                    errors.level && (
                        <>
                            {
                                errors.level.type === 'required' && <div>This field is required</div>
                            }
                            {
                                errors.level.type === 'validate' && <div>Minimum duration condition for this level is not met.</div>
                            }
                        </>
                    )
                }
                <Form.Group className="mb-4" controlId="abstract">
                    <Form.Label>Abstract</Form.Label>
                    <Form.Control
                        as="textarea"
                        rows={3}
                        {...register('abstract', { required: true, minLength: 20 })}
                    />
                </Form.Group>

                <Button type="submit" disabled={!isValid}>Add a session</Button>
            </Form>
        </div>
    );
}

export default AddSession;
