// github_dotnet/New folder/ascendion-fsd-jan-2025/demos/workshops-app/src/app/workshops/workshop-details/add-session-template-driven/add-session.component.ts
import { Component } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { JsonPipe } from '@angular/common';

import { ToastService } from '../../../common/toast.service';

import { SessionsService } from '../../sessions.service';
import ISession from '../../models/ISession';
@Component({
  selector: 'app-add-session',
  standalone: true,
  imports: [FormsModule, JsonPipe],
  templateUrl: './add-session.component.html',
  styleUrl: './add-session.component.scss',
})
export class AddSessionComponent {
  constructor(
    private activatedRoute: ActivatedRoute,
    private sessionsService: SessionsService,
    private router: Router,
    private toastService: ToastService
  ) {}

  addSession(addSessionForm: NgForm) {
    const id = +(this.activatedRoute.snapshot.parent?.paramMap.get(
      'id'
    ) as string);

    const newSession = {
      ...addSessionForm.value,
      workshopId: id,
      upvoteCount: 0,
      sequenceId: +addSessionForm.value.sequenceId,
      duration: +addSessionForm.value.duration,
    } as Omit<ISession, 'id'>;

    console.log(newSession);

    this.sessionsService.addSession(newSession).subscribe({
      next: (addedSession) => {
        this.toastService.add({
          message: `Added session with id = ${addedSession.id}`,
          className: 'bg-success text-light',
          duration: 5000,
        });

        // You can also use navigateByUrl()
        this.router.navigate(['/workshops', id]);
      },
      error: (error) => {
        this.toastService.add({
          message: `Unable to add the session - ${error.message}`,
          className: 'bg-danger text-light',
          duration: 5000,
        });
      },
    });
  }
}

<div class="d-flex justify-content-between align-items-center">
  <h2 class="my-3">Add a session</h2>
  <button class="btn btn-primary" id="list-sessions">List of sessions</button>
</div>

<hr />

<form
  id="add-session-form"
  #addSessionForm="ngForm"
  (ngSubmit)="addSession(addSessionForm)"
>
  <div class="mb-3">
    <label for="sequenceId" class="form-label">Sequence ID</label>

    <input
      type="text"
      class="form-control"
      id="sequenceId"
      name="sequenceId"
      required
      pattern="\d+"
      ngModel
      #sequenceId="ngModel"
      autocomplete="off"
    />
    <!-- Note how the JSON pipe is used for inspecting objects and thus useful for debugging! -->
    {{ sequenceId.errors | json }}
    {{ sequenceId.value }}
    <div>{{ "sequenceId.invalid = " + sequenceId.invalid }}</div>
    <div>{{ "sequenceId.valid = " + sequenceId.valid }}</div>
    <div>{{ "sequenceId.dirty =" + sequenceId.dirty }}</div>
    <div>{{ "sequenceId.touched =" + sequenceId.touched }}</div>

    @if( sequenceId.invalid && ( sequenceId.touched || sequenceId.dirty ) &&
    sequenceId.errors ) {
    <div class="error-message">
      @if(sequenceId.errors['required']) {
      <div>This is required</div>
      } @if(sequenceId.errors['pattern']) {
      <div>Provide a number</div>
      }
    </div>
    }
  </div>
  <div class="mb-3">
    <label for="name" class="form-label">Name</label>
    <input type="text" class="form-control" id="name" />
  </div>
  <div class="mb-3">
    <label for="speaker" class="form-label">Speaker</label>
    <input type="text" class="form-control" id="speaker" />
  </div>
  <div class="mb-3">
    <label for="duration" class="form-label">Duration</label>
    <input type="number" class="form-control" id="duration" />
  </div>
  <div class="mb-3">
    <label for="level" class="form-label">Level</label>
    <select class="form-select" id="level">
      <option value="Basic">Basic</option>
      <option value="Intermediate">Intermediate</option>
      <option value="Advanced">Advanced</option>
    </select>
  </div>
  <div class="mb-3">
    <label for="abstract" class="form-label">Abstract</label>
    <textarea class="form-control" id="abstract" rows="3"></textarea>
  </div>
  <div class="mb-3">
    <button class="btn btn-primary" [disabled]="addSessionForm.invalid">
      Add session
    </button>
  </div>
</form>

// ReactTs/ascendion-react-feb-2025/ReactApp/workshops-app/src/components/workshops/WorkshopDetails/AddSession/AddSession.tsx
import { FormEvent, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { Button, Form } from "react-bootstrap"

import { addSession } from '../../../../services/sessions';
import { Level } from '../../../../models/ISession';
interface Props {
    id: number
}

// uncontrolled components
const AddSession = ( { id } : Props) => {
    // sequenceIdRef.current = null
    // after the first render `current` will refer to the DOM node for the sequence ID input)
    const sequenceIdRef = useRef<HTMLInputElement>(null);
    const nameRef = useRef<HTMLInputElement>(null);
    const speakerRef = useRef<HTMLInputElement>(null);
    const durationRef = useRef<HTMLInputElement>(null);
    const levelRef = useRef<HTMLSelectElement>(null);
    const abstractRef = useRef<HTMLTextAreaElement>(null);

    const [sequenceIdError, setSequenceIdError] = useState('')

    const validate = () => {
        let isValid = true;

        if( sequenceIdRef.current ) {
            const sequenceId = sequenceIdRef.current.value;
            let sequenceIdError = '';

            if( sequenceId === '' ) {
                sequenceIdError += 'Sequence ID cannot be empty.';
                isValid = false;
            }

            if( sequenceId !== '' && /^\d+$/.test(sequenceId) === false ) {
                sequenceIdError += 'Sequence ID must be a positive number';
                isValid = false;
            }

            setSequenceIdError(sequenceIdError);

            // do all other checks
            // ..

            return isValid;
        }
    };

    const onSubmit = async (event: FormEvent<HTMLFormElement> ) => {
        // prevent browser form submssion
        event.preventDefault();

        if( sequenceIdRef.current && nameRef.current && speakerRef.current && durationRef.current && levelRef.current && abstractRef.current) {
            const session = {
                sequenceId: +sequenceIdRef.current.value,
                name: nameRef.current.value,
                speaker: speakerRef.current.value,
                duration: +durationRef.current.value,
                level: levelRef.current.value as Level,
                abstract: abstractRef.current.value,
                upvoteCount: 0,
                workshopId: id
            };

            console.log( session );

            if( validate() ) {
                // POST the new session information to create a new session
                try {
                    const newSession = await addSession( session );
                    alert('New session has been added');
                } catch(error) {
                    alert((error as Error).message);
                }
            } else {
                alert( 'Correct the mistakes in the form and submit again.' )
            }
        }
    }

    return (
        <div>
            <h1 className="d-flex justify-content-between align-items-center">
                Add a Session
                <Link to=".." className="btn btn-primary">List of sessions</Link>
            </h1>

            <hr />

            <Form onSubmit={onSubmit}>
                <Form.Group className="mb-4" controlId="sequenceId">
                    <Form.Label>Sequence ID</Form.Label>
                    <Form.Control
                        type="number"
                        placeholder="The Sequence ID of the session (eg. 1, 2, 3...)"
                        ref={sequenceIdRef}
                    />
                    <div className="text-danger">{sequenceIdError}</div>
                </Form.Group>
                <Form.Group className="mb-4" controlId="name">
                    <Form.Label>Name</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Name of the session, Eg. Introduction to Programming"
                        ref={nameRef}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="speaker">
                    <Form.Label>Speaker</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="Name of the speaker(s). Eg. John Doe, Jane Doe"
                        ref={speakerRef}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="duration">
                    <Form.Label>Duration</Form.Label>
                    <Form.Control
                        type="text"
                        placeholder="The duration of the session in hours (eg. 2.5)"
                        ref={durationRef}
                    />
                </Form.Group>
                <Form.Group className="mb-4" controlId="level">
                    <Form.Label>Level</Form.Label>
                    <Form.Select aria-label="Level" ref={levelRef}>
                        <option disabled>-- Select the level --</option>
                        <option value="Basic">Basic</option>
                        <option value="Intermediate">Intermediate</option>
                        <option value="Advanced">Advanced</option>
                    </Form.Select>
                </Form.Group>
                <Form.Group className="mb-4" controlId="abstract">
                    <Form.Label>Abstract</Form.Label>
                    <Form.Control
                        as="textarea"
                        rows={3}
                        ref={abstractRef}
                    />
                </Form.Group>

                <Button type="submit">Add a session</Button>
            </Form>
        </div>
    );
}

export default AddSession;
