// github_dotnet/github/ascendion-fsd-jan-2025/my_work/workshops-app/src/app/workshops/workshops-list/item/item.component.ts
import { Component, Input } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';
import { LocationPipe } from '../../../common/location.pipe';
import IWorkshop from '../../models/IWorkshop';

@Component({
  selector: 'app-item',
  standalone: true,
  imports: [DatePipe, LocationPipe, RouterLink],
  templateUrl: './item.component.html',
  styleUrl: './item.component.scss',
})
export class ItemComponent {
  @Input()
  workshop!: IWorkshop;
}
@if( workshop ) {
  <div class="card p-3">
    <div class="card-img-top-wrapper">
      <img [src]="workshop.imageUrl" class="card-img-top" [alt]="workshop.name" />
    </div>
    <div class="card-body">
      <h5 class="card-title my-0">{{ workshop.name }}</h5>
      <div class="card-text">
        <div>{{ workshop.time }}</div>
        <div>
          {{ workshop.startDate | date : "MMM dd, yyyy" }} -
          {{ workshop.endDate | date : "MMM dd, yyyy" }}
        </div>
        <div>
          {{ workshop.location | location : "short" : 32 }}
        </div>
      </div>
      <a [routerLink]="['/workshops', workshop.id]" class="btn btn-primary"
        >Know more</a
      >
    </div>
  </div>
  }

// ReactTs/CompleteReactTsAfterTraining/ascendion-react-feb-2025/demos/02-react/workshops-app/src/components/workshops/WorkshopsList/Item/Item.tsx
import { useContext } from "react";
import { Card, Button } from "react-bootstrap";
import { Link } from "react-router-dom";
import IWorkshop from "../../../../models/IWorkshop";
import FormattedDate from "../../../common/FormattedDate/FormattedDate";
import ThemeContext from "../../../../contexts/ThemeContext";

import './Item.scss';

const Item = ({ id, name, category, imageUrl, location, startDate, endDate }: IWorkshop ) => {
    const { theme  } = useContext(ThemeContext);

    return (
        <Card className="w-100 p-3" bg={theme}>
            <div className="card-img-top-wrapper">
                <Card.Img variant="top" src={imageUrl} alt={name} />
            </div>
            <Card.Body>
                <Card.Title>
                    {name} ({category})</Card.Title>
                <Card.Text>
                    <div>{location.address}, {location.city}, {location.state}</div>
                    <div>
                        <FormattedDate date={startDate} />
                        <span> - </span>
                        <FormattedDate date={endDate} />
                    </div>
                </Card.Text>
                <Link to={`/workshops/${id}`}>
                    <Button variant="primary">Know more</Button>
                </Link>
            </Card.Body>
        </Card>
    );
};

export default Item;
