// github_dotnet/New folder/ascendion-fsd-jan-2025/demos/workshops-app/src/app/workshops/workshops-list/item/item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DatePipe } from '@angular/common';

import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import {
  faPencilAlt as faPencil,
  faTrash,
} from '@fortawesome/free-solid-svg-icons';

import { LocationPipe } from '../../../common/location.pipe';
import IWorkshop from '../../models/IWorkshop';

@Component({
  selector: 'app-item',
  standalone: true,
  imports: [DatePipe, LocationPipe, RouterLink, FontAwesomeModule],
  templateUrl: './item.component.html',
  styleUrl: './item.component.scss',
})
export class ItemComponent {
  @Input()
  workshop!: IWorkshop;

  @Output()
  delete = new EventEmitter();

  icons = {
    faPencil,
    faTrash,
  };

  onDeleteWorkshop() {
    this.delete.emit();
  }
}

@if( workshop ) {
<div class="card p-3">
  <div class="card-action-buttons">
    <button
      class="me-2 btn btn-info btn-sm btn-action-button"
      title="Edit this workshop"
    >
      <fa-icon [icon]="icons.faPencil"></fa-icon>
    </button>
    <button
      class="btn btn-danger btn-sm"
      title="Delete this workshop"
      (click)="onDeleteWorkshop()"
    >
      <fa-icon [icon]="icons.faTrash"></fa-icon>
    </button>
  </div>

  <div class="card-img-top-wrapper">
    <img [src]="workshop.imageUrl" class="card-img-top" [alt]="workshop.name" />
  </div>
  <div class="card-body">
    <h5 class="card-title my-0">{{ workshop.name }}</h5>
    <div class="card-text">
      <div>{{ workshop.time }}</div>
      <div>
        {{ workshop.startDate | date : "MMM dd, yyyy" }} -
        {{ workshop.endDate | date : "MMM dd, yyyy" }}
      </div>
      <div>
        {{ workshop.location | location : "short" : 32 }}
      </div>
    </div>
    <a [routerLink]="['/workshops', workshop.id]" class="btn btn-primary"
      >Know more</a
    >
  </div>
</div>
}

// ReactTs/CompleteReactTsAfterTraining/ascendion-react-feb-2025/workshops-app-completed/src/components/workshops/WorkshopsList/Item/Item.tsx
import { Card, Button } from "react-bootstrap";
import { Link } from "react-router-dom";

import FormattedDate from "../../../common/FormattedDate/FormattedDate";

import IWorkshop from "../../../../models/IWorkshop";

import './Item.scss';

const Item = ({ name, id, imageUrl, location, startDate, endDate }: IWorkshop) => {
    return (
        <Card className="w-100 p-3">
            <div className="card-img-top-wrapper">
                <Card.Img variant="top" src={imageUrl} alt={name} />
            </div>
            <Card.Body>
                <Card.Title>{name}</Card.Title>
                <Card.Text as="div">
                    <div>{location.address}, {location.city}, {location.state}</div>
                    <div>
                        <FormattedDate date={startDate} />
                        <span> - </span>
                        <FormattedDate date={endDate} />
                    </div>
                </Card.Text>
                <Link to={`/workshops/${id}`}>
                    <Button variant="primary">Know more</Button>
                </Link>
            </Card.Body>
        </Card>
    );
};

export default Item;
