// ReactTs/ascendion-react-feb-2025/ReactApp/workshops-app/src/components/Home/Home.tsx
// sfc + Enter
const Home = () => {
    return (
        <>
            <h1>Workshops App</h1>

            <hr />

            <section>
                <p>Welcome to Workshops App</p>
                <p>
                    The app serves details of (fictitious) technical workshops happening in
                    various cities. Every workshop has a broad topic (eg. JavaScript), and a
                    workshop has many sessions (each session covers a sub-topic, eg. Closures in
                    JavaScript).
                </p>
                <p>
                    You can view a list of workshops, details of every workshop, add a workshop,
                    view the list of sessions in a workshop, and also add a new session for a
                    workshop.
                </p>
            </section>
        </>
    );
}

export default Home;

// github_dotnet/New folder/ascendion-fsd-jan-2025/demos/workshops-app/src/app/home/home.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent {
  public title = 'Workshops Application';
  // public count = 0;

  // public changeTitle() {
  //   this.title = 'My first Angular Application';
  //   ++this.count;
  // }
}

<!-- <h1>{{ title }}</h1>
<hr />
<button (click)="changeTitle()" class="btn btn-primary me-2">
  Change title
</button>
<span>
  You have clicked this button <span>{{ count }}</span> times
</span> -->
<h1>{{ title }}</h1>
<hr />
<p>
  The app serves details of (fictitious) technical workshops happening in
  various cities. Every workshop has a broad topic (eg. JavaScript), and a
  workshop has many sessions (each session covers a sub-topic, eg. Closures in
  JavaScript).
</p>
<p>
  You can view a list of workshops, details of every workshop, add a workshop,
  view the list of sessions in a workshop, and also add a new session for a
  workshop.
</p>
