// ReactTs/CompleteReactTsAfterTraining/ascendion-react-feb-2025/workshops-app-completed/src/components/workshops/WorkshopsList/WorkshopsList.tsx
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Col, Row } from "react-bootstrap";

import LoadingSpinner from "../../common/LoadingSpinner/LoadingSpinner";
import ErrorAlert from "../../common/ErrorAlert/ErrorAlert";
import Pagination from "../../common/Pagination/Pagination";

import Item from "./Item/Item";

import { getWorkshops } from "../../../services/workshops";
import IWorkshop from "../../../models/IWorkshop";

// uuid -> unique id generator library

const WorkshopsList = () => {
    const [loading, setLoading] = useState(true);
    const [workshops, setWorkshops] = useState<IWorkshop[]>([]);
    const [error, setError] = useState<Error | null>(null);

    const [filterKey, setFilterKey] = useState('');
    const [filteredWorkshops, setFilteredWorkshops] = useState<IWorkshop[]>([]);

    // const [page, setPage] = useState(1);
    const [searchParams, setSearchParams] = useSearchParams();
    const page = +(searchParams.get("page") || "1"); // Default to page 1
    const category = searchParams.get("category") || "";

    // side-effect -> eg. we want to fetch workshops data from the backend
    useEffect(
        () => {
            const helper = async () => {
                setLoading(true);

                try {
                    const workshops = await getWorkshops(page, category);
                    // console.log(workshops);
                    setWorkshops(workshops);
                    setLoading(false);
                } catch (error) {
                    // console.log(error);
                    setError(error as Error);
                    setLoading(false);
                }
            };

            helper();
        },
        // [ ] // empty array -> causes the effect to execute only AFTER first render
        [page, category] // execute AFTER first render + whenever page change
    );

    // side-effect for filtering when filterKey or workshops states change
    useEffect(
        () => {
            setFilteredWorkshops(
                workshops.filter(
                    (workshop) => workshop.name.toUpperCase().includes(filterKey.toUpperCase())
                )
            );
        },
        [workshops, filterKey]
    );

    const previous = (newPage: number) => {
        if (page <= 1) {
            return;
        }

        // when the new state depends on the current state, we use the function form of the setter
        // setPage((p) => p - 1);
        setSearchParams({ page: '' + newPage });
    };

    const next = (newPage: number) => {
        setSearchParams({ page: '' + newPage });
    };

    return (
        <div>
            <h1>List of workshops</h1>
            <hr />
            <div>
                <Pagination
                    page={page}
                    onPrevious={previous}
                    onNext={next}
                    disablePrevious={!(loading === false && error === null)}
                    disableNext={!(loading === false && error === null)}
                />
            </div>
            <div>
                <input
                    type="search"
                    className="form-control"
                    placeholder="Type to search by name"
                    value={filterKey}
                    onChange={(event) => setFilterKey(event.target.value)}
                />
                <div>
                    Workshops whose name has
                    <span className="text-primary"> {filterKey} </span> are shown.
                </div>
            </div>
            <div>
                <div className="btn-group my-3" role="group" aria-label="Filter by category">
                    <button type="button" className="btn btn-primary" onClick={() => setSearchParams({ category: '' })}>All</button>
                    <button type="button" className="btn btn-danger" onClick={() => setSearchParams({ category: 'frontend' })}>Frontend</button>
                    <button type="button" className="btn btn-warning" onClick={() => setSearchParams({ category: 'backend' })}>Backend</button>
                    <button type="button" className="btn btn-success" onClick={() => setSearchParams({ category: 'devops' })}>Devops</button>
                    <button type="button" className="btn btn-info" onClick={() => setSearchParams({ category: 'language' })}>Language</button>
                    <button type="button" className="btn btn-light" onClick={() => setSearchParams({ category: 'mobile' })}>Mobile</button>
                    <button type="button" className="btn btn-dark" onClick={() => setSearchParams({ category: 'database' })}>Database</button>
                </div>
            </div>
            {
                /* if..else */
                loading ? <LoadingSpinner variant="success" /> : <div>Completed loading</div>
            }
            {
                /* if */
                loading === false && error !== null && (
                    <ErrorAlert error={error} />
                )
            }
            {loading === false && error === null && (
                <Row xs={1} md={3} lg={4}>
                    {filteredWorkshops.map((workshop, idx) => (
                        <Col className="my-3 d-flex" key={workshop.id}>
                            <Item {...workshop} />
                        </Col>
                    ))}
                </Row>
            )}
            {/*
                {
                    [
                        <div key={workshops[0].id}>{workshops[0].name}</div>,
                        <div key={workshops[1].id}>{workshops[1].name}</div>,
                        <div>{workshops[2].name}</div>,
                        <div>{workshops[3].name}</div>,
                        ....
                    ]
                */}
        </div>
    );
};

export default WorkshopsList;

// github_dotnet/github/ascendion-fsd-jan-2025/my_work/workshops-app/src/app/workshops/workshops-list/workshops-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';

import { LoadingSpinnerComponent } from '../../common/loading-spinner/loading-spinner.component';
import { ErrorAlertComponent } from '../../common/error-alert/error-alert.component';
import { PaginationComponent } from '../../common/pagination/pagination.component';
import { ItemComponent } from './item/item.component';
import { WorkshopsService } from '../workshops.service';
import IWorkshop from '../models/IWorkshop';

@Component({
  selector: 'app-workshops-list',
  standalone: true,
  imports: [
    FormsModule,
    LoadingSpinnerComponent,
    ErrorAlertComponent,
    PaginationComponent,
    ItemComponent,
  ],
  templateUrl: './workshops-list.component.html',
  styleUrl: './workshops-list.component.scss',
})
export class WorkshopsListComponent implements OnInit {
  loading = true;
  error: Error | null = null;
  workshops!: IWorkshop[];
  page = 1;

  filterKey = '';
  filteredWorkshops!: IWorkshop[];

  // private ws: WorkshopsService;

  // constructor(ws: WorkshopsService) {
  //   this.ws = ws;

  //   console.log(this.ws);
  // }

  // Dependency Injection (DI)
  constructor(
    private ws: WorkshopsService,
    private router: Router,
    private activatedRoute: ActivatedRoute
  ) {}

  getWorkshops() {
    this.loading = true;
    console.log(this.ws);

    this.ws.getWorkshops(this.page).subscribe({
      // success
      next: (data) => {
        this.workshops = data;
        this.filteredWorkshops = this.workshops;
        this.loading = false;
      },

      // error
      error: (err) => {
        this.error = err;
        this.loading = false;
      },
    });
  }

  // LIFECYCLE METHOD OF COMPONENT
  public ngOnInit() {
    // this.getWorkshops();

    // this.activatedRoute.queryParamMap is an Observable that tracks changes to the query string -> thus whenever `page` in the query string changes, the next() method is called
    this.activatedRoute.queryParamMap.subscribe({
      next: (queryParams) => {
        const queryStr = queryParams.get('page');

        // when the page loads for the first time, there is no `page` query string parameter -> so we set page to 1. Later on there is some `page` value
        if (queryStr === null) {
          this.page = 1;
        } else {
          this.page = +queryStr; // convert `page` from string type to number
        }

        this.getWorkshops(); // page has changed -> get fresh data
      },
    });
  }

  // Just before the component is removed from DOM
  ngOnDestroy() {}

  changePage(newPage: number) {
    this.page = newPage;

    // this.getWorkshops();

    // set the query string in the route
    this.router.navigate(['/workshops'], {
      queryParams: {
        page: this.page,
      },
    });
  }

  filterWorkshops() {
    this.filteredWorkshops = this.workshops.filter((w) =>
      w.name.toLowerCase().includes(this.filterKey.toLowerCase())
    );
  }

  filterByCategory(category: string) {
    this.ws.getWorkshops(this.page, category).subscribe({
      next: (workshops) => {
        this.workshops = workshops;
        // A better alternative: If you make `this.workshops` and `this.filterKey` as signals, you can compute `this.filteredWorkshops` automatically when either `this.workshops` changes or `this.filterKey` changes
        this.filterWorkshops();
      },
    });
  }
}
@if( loading ) {
  <app-loading-spinner variant="success"></app-loading-spinner>
  } @else if( error !== null ) {
  <app-error-alert [error]="error"></app-error-alert>
  } @else {
  <app-pagination
    [page]="page"
    (pageChange)="changePage($event)"
  ></app-pagination>
  
  <input
    type="search"
    class="form-control"
    placeholder="Type to search by name"
    [(ngModel)]="filterKey"
    (input)="filterWorkshops()"
  />
  
  @if ( filterKey !== '' ) {
  <div>
    Workshops whose name has
    <span class="text-primary">{{ filterKey }}</span> are shown.
  </div>
  }
  
  <div class="btn-group my-3" role="group" aria-label="Filter by category">
    <button
      type="button"
      class="btn btn-danger"
      (click)="filterByCategory('frontend')"
    >
      Frontend
    </button>
    <button
      type="button"
      class="btn btn-warning"
      (click)="filterByCategory('backend')"
    >
      Backend
    </button>
    <button
      type="button"
      class="btn btn-success"
      (click)="filterByCategory('devops')"
    >
      Devops
    </button>
    <button
      type="button"
      class="btn btn-info"
      (click)="filterByCategory('language')"
    >
      Language
    </button>
    <button
      type="button"
      class="btn btn-light"
      (click)="filterByCategory('mobile')"
    >
      Mobile
    </button>
    <button
      type="button"
      class="btn btn-dark"
      (click)="filterByCategory('database')"
    >
      Database
    </button>
  </div>
  
  <div class="row">
    @for( workshop of filteredWorkshops; track workshop.id ) {
    <div class="col-12 col-md-4 my-3 d-flex">
      <app-item [workshop]="workshop"></app-item>
    </div>
    }
  </div>
  }
