// BodhaRepo/BodhaReactRepo/Video-catalog/video-catalog/src/components/common/Menu/Menu.tsx
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';
import { Link } from 'react-router';

const Menu = () => {
    return (
        <Navbar collapseOnSelect expand="lg" className="bg-light">
            <Container>
                <Navbar.Brand href="/">Movie List App</Navbar.Brand>

                <Navbar.Toggle aria-controls="responsive-navbar-nav" />

                <Navbar.Collapse id="responsive-navbar-nav">
                    <Nav className="me-auto">
                        {/* <Nav.Link href="/">Home</Nav.Link> */}
                        
                        <Nav.Link as={Link} to="/MovieList" >List of Movies</Nav.Link>

                    </Nav>
                    <NavDropdown title="Personalize" id="basic-nav-dropdown">
                        {/* <NavDropdown.Item href="#">
                            Favorites
                        </NavDropdown.Item> */}
                        <NavDropdown.Item href="#">
                            Change Theme
                        </NavDropdown.Item>
                    </NavDropdown>
                </Navbar.Collapse>
            </Container>
        </Navbar>
    );
};

export default Menu;

// github_dotnet/New folder/ascendion-fsd-jan-2025/demos/workshops-app/src/app/menu/menu.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [NgbModule, RouterLink, RouterLinkActive],
  templateUrl: './menu.component.html',
  styleUrl: './menu.component.scss',
})
export class MenuComponent {
  public isNavbarCollapsed = true;
}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Workshops App</a>
    <button
      class="navbar-toggler"
      type="button"
      (click)="isNavbarCollapsed = !isNavbarCollapsed"
      aria-controls="navbarNav"
      aria-expanded="!isNavbarCollapsed"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      id="navbarNav"
      [ngbCollapse]="isNavbarCollapsed"
      class="collapse navbar-collapse"
    >
      <!-- left menu -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            routerLink="/"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            routerLink="/workshops"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
            >List of workshops</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            routerLink="/workshops/add"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
            >Add a workshop</a
          >
        </li>
      </ul>

      <!-- right menu (no .me-auto)-->
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item" ngbDropdown>
          <a
            class="nav-link"
            tabindex="0"
            ngbDropdownToggle
            id="navbarDropdown1"
            role="button"
          >
            Account & Preferences
          </a>
          <div
            ngbDropdownMenu
            aria-labelledby="navbarDropdown1"
            class="dropdown-menu"
          >
            <a
              ngbDropdownItem
              routerLink="/workshops/favorites"
              routerLinkActive="active"
              [routerLinkActiveOptions]="{ exact: true }"
              >Favorites</a
            >
            <a ngbDropdownItem href="#" (click)="$event.preventDefault()"
              >Logout</a
            >
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>
