// github_dotnet/github/ascendion-fsd-jan-2025/my_work/workshops-app/src/app/common/loading-spinner/loading-spinner.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Theme } from '../../models/utils';

@Component({
  selector: 'app-loading-spinner',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './loading-spinner.component.html',
  styleUrl: './loading-spinner.component.scss',
})
export class LoadingSpinnerComponent {
  @Input()
  variant!: Theme;
}
<!-- Alternative -->
<!-- getLoadingClass() can return the name of the class-->
<!-- [ngClass]="getLoadingClass()" -->
<!-- Exercise: Explore ngStyle -->
<div
  class="text-center"
  [ngClass]="{
  'text-primary': variant === 'primary',
  'text-secondary': variant === 'secondary',
  'text-danger': variant === 'danger',
  'text-success': variant === 'success',
  'text-warning': variant === 'warning',
  'text-info': variant === 'info',
  'text-light': variant === 'light',
  'text-dark': variant === 'dark',
}"
>
  <div class="spinner-border" role="status">
    <span class="visually-hidden">Loading...</span>
  </div>
</div>

// ReactTs/CompleteReactTsAfterTraining/ascendion-react-feb-2025/workshops-app-completed/src/components/common/LoadingSpinner/LoadingSpinner.tsx
import { Spinner } from "react-bootstrap";
import type { Theme } from '../../../models/utils';

interface Props {
    variant: Theme
}

const LoadingSpinner = ( { variant } : Props ) => {
    return (
        <div className="text-center">
            <Spinner animation="border" role="status" variant={variant}>
                <span className="visually-hidden">Loading...</span>
            </Spinner>
        </div>
    );
};

export default LoadingSpinner;
